name:                VigierFRL
version:             0.1.0.0
github:              "francovigier/ALPFINAL2022"
license:             GPL-3
author:              "Franco Vallejos Vigier"
maintainer:          "francovallejosvigier@gmail.com"
copyright:           "2022 Franco Vigier"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         TPFINALVIGIERALP2022

dependencies:
- base >= 4.7 && < 5
- haskeline
- array
- parsec
- pretty
- mtl
- exceptions
- bytestring
- filepath
- binary
- optparse-applicative
- prettyprinter
- prettyprinter-ansi-terminal
- extra
- text



library:
  source-dirs: src

executables:
  VigierFRL-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-tabs
    - -fwarn-unused-imports
    - -fwarn-missing-signatures
    - -fwarn-name-shadowing
    - -fwarn-incomplete-patterns
    dependencies:
    - VigierFRL
    build-tools:
    - happy